// <auto-generated />
using System;
using DanielSchool.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DanielSchool.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20221116022632_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DanielSchool.Core.Domain.Entities.Asignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GradoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ttle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.ToTable("Asignacion");
                });

            modelBuilder.Entity("DanielSchool.Core.Domain.Entities.Calificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentaries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExtraPoints")
                        .HasColumnType("int");

                    b.Property<int>("GradoId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<int>("Notes")
                        .HasColumnType("int");

                    b.Property<string>("ProfesorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.ToTable("Calificacion");
                });

            modelBuilder.Entity("DanielSchool.Core.Domain.Entities.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.ToTable("Grado");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "4to",
                            Section = "A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "4to",
                            Section = "B"
                        },
                        new
                        {
                            Id = 3,
                            Name = "5to",
                            Section = "A"
                        },
                        new
                        {
                            Id = 4,
                            Name = "5to",
                            Section = "B"
                        },
                        new
                        {
                            Id = 5,
                            Name = "6to",
                            Section = "A"
                        },
                        new
                        {
                            Id = 6,
                            Name = "6to",
                            Section = "B"
                        },
                        new
                        {
                            Id = 7,
                            Name = "7mo",
                            Section = "A"
                        },
                        new
                        {
                            Id = 8,
                            Name = "7mo",
                            Section = "B"
                        },
                        new
                        {
                            Id = 9,
                            Name = "8vo",
                            Section = "A"
                        },
                        new
                        {
                            Id = 10,
                            Name = "8vo",
                            Section = "B"
                        },
                        new
                        {
                            Id = 11,
                            Name = "9no",
                            Section = "A"
                        },
                        new
                        {
                            Id = 12,
                            Name = "9no",
                            Section = "B"
                        },
                        new
                        {
                            Id = 13,
                            Name = "10mo",
                            Section = "A"
                        },
                        new
                        {
                            Id = 14,
                            Name = "10mo",
                            Section = "B"
                        },
                        new
                        {
                            Id = 15,
                            Name = "11vo",
                            Section = "A"
                        },
                        new
                        {
                            Id = 16,
                            Name = "11vo",
                            Section = "B"
                        },
                        new
                        {
                            Id = 17,
                            Name = "12vo",
                            Section = "A"
                        },
                        new
                        {
                            Id = 18,
                            Name = "12vo",
                            Section = "B"
                        });
                });

            modelBuilder.Entity("DanielSchool.Core.Domain.Entities.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Publish")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Noticia");
                });

            modelBuilder.Entity("DanielSchool.Core.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("DanielSchool.Core.Domain.Entities.Grado", "NP_grado")
                        .WithMany("NP_asignations")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NP_grado");
                });

            modelBuilder.Entity("DanielSchool.Core.Domain.Entities.Calificacion", b =>
                {
                    b.HasOne("DanielSchool.Core.Domain.Entities.Grado", "NP_grado")
                        .WithMany("NP_calificacions")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NP_grado");
                });

            modelBuilder.Entity("DanielSchool.Core.Domain.Entities.Grado", b =>
                {
                    b.Navigation("NP_asignations");

                    b.Navigation("NP_calificacions");
                });
#pragma warning restore 612, 618
        }
    }
}
